FROM mcr.microsoft.com/dotnet/sdk:10.0

WORKDIR /app

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Development

ENTRYPOINT ["dotnet", "watch", "run", "--project", "src/WebTemplate.Api", "--no-hot-reload"]
